[package]
name = "fumetto-probe"
version.workspace = true
edition = "2024"
license.workspace = true

[dependencies]
fast_image_resize = "6.1.0"
fumetto = { path = "../fumetto" }
fumetto-core = { path = "../fumetto-core" }
fumetto-render = { path = "../fumetto-render" }
image = { version = "0.25.10", default-features = false, features = ["png"] }
pollster = "1.0.1"
